name: Build

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  example:
    name: os:${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-13
          - macos-14
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Clone Spack
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: spack/spack
          path: spack
      - name: Add Spack to PATH and set mirror name
        run: |
          echo "${PWD}/spack/bin" >> "${GITHUB_PATH}"
      - name: Print Spack configuration
        run: |
          spack compiler find
          spack compilers
          spack config blame config
          spack debug report
      - name: Install
        run: |
          spack install berkeley-db
